/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./src/muscles/scene.gltf --transform 
Files: ./src/muscles/scene.gltf [3.88KB] > /home/miguel/codes/human_body/human_body/scene-transformed.glb [42.8KB] (-1003%)
Author: artyom.changlyan (https://sketchfab.com/artyom.changlyan)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-human-anatomy-0be4d79f6f9b4bea8c2dca7f20479e92
Title: low poly human anatomy
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Scene_-_Root']} position={[0, 7.408, 0]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
